-- MySQL Script generated by MySQL Workbench
-- Mon May 12 19:43:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartlab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartlab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `smartlab` ;

-- -----------------------------------------------------
-- Table `smartlab`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`setor` (
  `idSetor` INT NOT NULL AUTO_INCREMENT,
  `Nome_setor` VARCHAR(20) NULL DEFAULT NULL,
  `Capacidade` VARCHAR(4) NULL DEFAULT NULL,
  `Descricao` VARCHAR(70) NULL DEFAULT NULL,
  `Localizacao` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idSetor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`ambientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`ambientes` (
  `idAmbiente` INT NOT NULL AUTO_INCREMENT,
  `idSetor` INT NULL DEFAULT NULL,
  `nomeAmbiente` VARCHAR(50) NOT NULL,
  `tipoAmbiente` VARCHAR(50) NULL DEFAULT NULL,
  `capacidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idAmbiente`),
  INDEX `idSetor` (`idSetor` ASC) VISIBLE,
  CONSTRAINT `ambientes_ibfk_1`
    FOREIGN KEY (`idSetor`)
    REFERENCES `smartlab`.`setor` (`idSetor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nomecurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`usuarios` (
  `idUsuario` INT(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL,
  `Senha` VARCHAR(125) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `fk_idcurso` INT NULL,
  `tipo_usuario` ENUM('admin', 'user') NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuarios_curso2_idx` (`fk_idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_curso2`
    FOREIGN KEY (`fk_idcurso`)
    REFERENCES `smartlab`.`curso` (`idcurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`apikeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`apikeys` (
  `idAPIKey` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `api_key` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`idAPIKey`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `apikeys_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`autenticacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`autenticacao` (
  `idAutenticacao` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `perfil` ENUM('admin', 'usuario') NULL DEFAULT NULL,
  PRIMARY KEY (`idAutenticacao`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `autenticacao_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`disponibilidade` (
  `iddisponibilidade` INT NOT NULL,
  `fkid_ambiente` INT NOT NULL AUTO_INCREMENT,
  `dias` INT NOT NULL,
  `horainicio` TIME NOT NULL,
  `horafim` TIME NOT NULL,
  `status` ENUM('disponivel', 'indisponivel') NOT NULL,
  PRIMARY KEY (`iddisponibilidade`),
  INDEX `fk_disponibilidade_ambientes1_idx` (`fkid_ambiente` ASC) VISIBLE,
  CONSTRAINT `fk_disponibilidade_ambientes1`
    FOREIGN KEY (`fkid_ambiente`)
    REFERENCES `smartlab`.`ambientes` (`idAmbiente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`perifericos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`perifericos` (
  `idPerifericos` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  `quantidade_inicial` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPerifericos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_perifericos` INT NULL DEFAULT NULL,
  `dataHora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('ativo', 'cancelado') NULL DEFAULT 'ativo',
  `fk_iddisponibilidade` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_id_usuario` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_id_perifericos` (`fk_id_perifericos` ASC) VISIBLE,
  INDEX `fk_reserva_disponibilidade1_idx` (`fk_iddisponibilidade` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_disponibilidade1`
    FOREIGN KEY (`fk_iddisponibilidade`)
    REFERENCES `smartlab`.`disponibilidade` (`iddisponibilidade`),
  CONSTRAINT `reserva_ibfk_1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`),
  CONSTRAINT `reserva_ibfk_4`
    FOREIGN KEY (`fk_id_perifericos`)
    REFERENCES `smartlab`.`perifericos` (`idPerifericos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`feedback` (
  `idFeedback` INT NOT NULL AUTO_INCREMENT,
  `idReserva` INT NULL DEFAULT NULL,
  `idUsuario` INT NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `nota` INT NULL DEFAULT NULL,
  `dataFeedback` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idFeedback`),
  INDEX `idReserva` (`idReserva` ASC) VISIBLE,
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `feedback_ibfk_1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `smartlab`.`reserva` (`idReserva`),
  CONSTRAINT `feedback_ibfk_2`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`historicoreservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`historicoreservas` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('ativa', 'cancelada', 'concluída') NULL DEFAULT NULL,
  `datareserva` DATETIME NOT NULL,
  `fk_idreserva` INT NOT NULL,
  PRIMARY KEY (`idHistorico`),
  INDEX `fk_historicoreservas_reserva1_idx` (`fk_idreserva` ASC) VISIBLE,
  CONSTRAINT `fk_historicoreservas_reserva1`
    FOREIGN KEY (`fk_idreserva`)
    REFERENCES `smartlab`.`reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`logs` (
  `idLog` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `acao` VARCHAR(255) NULL DEFAULT NULL,
  `dataHora` DATETIME NULL DEFAULT NULL,
  `detalhes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `logs_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smartlab`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartlab`.`notificacoes` (
  `idNotificacao` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `mensagem` TEXT NULL DEFAULT NULL,
  `dataEnvio` DATETIME NULL DEFAULT NULL,
  `statusLido` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`idNotificacao`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `notificacoes_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `smartlab`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `smartlab` ;

-- -----------------------------------------------------
-- procedure DeleteReserva
-- -----------------------------------------------------

DELIMITER $$
USE `smartlab`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DeleteReserva`(
    IN p_idReserva INT,
    IN p_fk_id_horario INT,
    IN p_ambientes_idAmbiente INT,
    IN p_fk_id_perifericos INT
)
BEGIN
    UPDATE ambientes SET disponibilidade = 1 WHERE idAmbiente = p_ambientes_idAmbiente;
    UPDATE horarios SET disponivel = 1 WHERE idHorarios = p_fk_id_horario;
    UPDATE perifericos SET Quantidade = quantidade_inicial WHERE idPerifericos = p_fk_id_perifericos;
    DELETE FROM reserva WHERE idReserva = p_idReserva;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function ListarReservasAtivas
-- -----------------------------------------------------

DELIMITER $$
USE `smartlab`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `ListarReservasAtivas`(p_id_usuario INT) RETURNS longtext CHARSET utf8mb4 COLLATE utf8mb4_bin
    READS SQL DATA
    DETERMINISTIC
BEGIN
    DECLARE resultado JSON;
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
            'idReserva', idReserva,
            'fk_id_horario', fk_id_horario,
            'fk_id_perifericos', fk_id_perifericos,
            'dataHora', dataHora,
            'ambientes_idAmbiente', ambientes_idAmbiente,
            'status', status
        )
    ) INTO resultado
    FROM reserva
    WHERE fk_id_usuario = p_id_usuario AND status = 'ativo';

    RETURN resultado;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_inserir_reserva
-- -----------------------------------------------------

DELIMITER $$
USE `smartlab`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_inserir_reserva`(
    IN p_id_usuario INT,
    IN p_id_setor INT,
    IN p_id_horario INT,
    IN p_id_perifericos INT,
    IN p_data_reserva DATETIME
)
BEGIN
    DECLARE new_reserva_id INT;
    INSERT INTO reserva (fk_id_usuario, fk_id_horario, fk_id_perifericos, dataHora)
    VALUES (p_id_usuario, p_id_horario, p_id_perifericos, p_data_reserva);

    SET new_reserva_id = LAST_INSERT_ID();

    INSERT INTO logs (idUsuario, acao, dataHora, detalhes)
    VALUES (p_id_usuario, 'Reserva criada', NOW(), CONCAT('Reserva ID: ', new_reserva_id));
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
