@startuml 
[*] --> Pendente

Pendente --> Confirmada: Aprovar Reserva
Pendente --> Cancelada: Cancelar Reserva

Confirmada --> Cancelada: Cancelar Reserva
Confirmada --> [*]: Finalizar

Cancelada --> [*]
@enduml
